version: '3.9'
services:
  app:
    build: 
     context: .
     args:
      - DEV=${DEV}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    env_file:
      - .env
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo